version: '3.8'
services:
  django:
    image: django-service1
    container_name: yiannis_pana_django_devops
    build:
      dockerfile: ./application_django/Dockerfile
      context: .
    env_file:
      -  ./application_django/.env
    ports:
      - "7539:7539"
    volumes:
      - ./application_django/devops:/application_django
      - ./logs/service2.log://application_django/logs/service2.log
    networks:
        dev_ops_ex1:
          ipv4_address: 172.21.0.2
  nodejs:
    image: nodejs-service2
    container_name: yiannis_pana_nodejs_devops
    build:
      dockerfile: ./application_node_js/Dockerfile
      context: .
    env_file:
      -  ./application_node_js/.env
    ports:
      - "8000:8000"
    volumes:
      - ./application_node_js:/application_node_js
      - ./logs/service1.log:/application_node_js/logs/service1.log
    depends_on:
        - django
    networks:
       dev_ops_ex1:
          ipv4_address: 172.21.0.3
networks:
  dev_ops_ex1:
    name: devops_yiannis_pana_exercise_one
    ipam:
      config:
        - subnet: 172.21.0.0/16
          ip_range: 172.21.0.0/24
    external: false #internal network
volumes:
  static_volume: null
